#pragma once


typedef enum error_e {
	ERROR_OK,
	ERROR_ELF_HEADERS,
	ERROR_OPEN_FILE,
	ERROR_INVALID_ARGUMENT,
	ERROR_NOT_FOUND,
	ERROR_ILLEGAL_INSTRUCTION,
	ERROR_UNALLOCATED_MEMORY,
	ERROR_ADDRESS_NOT_ALIGNED,
	ERROR_UNINIT_MEMORY,
	ERROR_UNSUPPORTED_SYSCALL,
	ERROR_ILLEGAL_SYSCALL,

} error_t;

#define IS_SUCCESS(err) (err == ERROR_OK)
