#include "instructions.h"

#include "instruction_handlers.h"
instruction_entry_t instructions[] =
{
	/*position in array is opcode*/
	{R_INSTRUCTION, NULL, handle_r_functs, {0}},
	{
		I_INSTRUCTION, NULL, handle_bgez_specials,
		{INSTRUCTION_PART_RT, {{0x0, "bltz"}, {0x01, "bgez"}, {0x10, "bltzal"}, {0x11, "bgezal"}}}
	},
	{J_INSTRUCTION, "j", handle_j, {0}},
	{J_INSTRUCTION, "jal", handle_jal, {0}},
	{I_INSTRUCTION, "beq", handle_beq, {0}},
	{I_INSTRUCTION, "bne", handle_bne, {0}},
	{I_INSTRUCTION, "blez", handle_blez, {0}},
	{I_INSTRUCTION, "bgtz", handle_bgtz, {0}},
	{I_INSTRUCTION, "addi", handle_addi, {0}},
	{I_INSTRUCTION, "addiu", handle_addiu, {0}},
	{I_INSTRUCTION, "slti", handle_slti, {0}},
	{I_INSTRUCTION, "sltiu", handle_sltiu, {0}},
	{I_INSTRUCTION, "andi", handle_andi, {0}},
	{I_INSTRUCTION, "ori", handle_ori, {0}},
	{I_INSTRUCTION, "xori", handle_xori, {0}},
	{I_INSTRUCTION, "lui", handle_lui, {0}},
	{
		R_INSTRUCTION, NULL, handle_mfc0_mft0,
		{INSTRUCTION_PART_RS, {{0x0, "mfc0"}, {0x4, "mtc0"}, NULL, {0}, NULL, {0}}}
	},
	{ILLEGAL_INSTRUCTION, NULL, NULL, {0}},
	{ILLEGAL_INSTRUCTION, NULL, NULL, {0}},
	{ILLEGAL_INSTRUCTION, NULL, NULL, {0}},
	{ILLEGAL_INSTRUCTION, NULL, NULL, {0}},
	{ILLEGAL_INSTRUCTION, NULL, NULL, {0}},
	{ILLEGAL_INSTRUCTION, NULL, NULL, {0}},
	{ILLEGAL_INSTRUCTION, NULL, NULL, {0}},
	{ILLEGAL_INSTRUCTION, NULL, NULL, {0}},
	{ILLEGAL_INSTRUCTION, NULL, NULL, {0}},
	{ILLEGAL_INSTRUCTION, NULL, NULL, {0}},
	{ILLEGAL_INSTRUCTION, NULL, NULL, {0}},
	{ILLEGAL_INSTRUCTION, NULL, NULL, {0}},
	{ILLEGAL_INSTRUCTION, NULL, NULL, {0}},
	{ILLEGAL_INSTRUCTION, NULL, NULL, {0}},
	{ILLEGAL_INSTRUCTION, NULL, NULL, {0}},
	{I_INSTRUCTION, "lb", handle_lb, {0}},
	{I_INSTRUCTION, "lh", handle_lh, {0}},
	{ILLEGAL_INSTRUCTION, NULL, NULL, {0}},
	{I_INSTRUCTION, "lw", handle_lw, {0}},
	{I_INSTRUCTION, "lbu", handle_lbu, {0}},
	{I_INSTRUCTION, "lhu", handle_lhu, {0}},
	{ILLEGAL_INSTRUCTION, NULL, NULL, {0}},
	{ILLEGAL_INSTRUCTION, NULL, NULL, {0}},
	{I_INSTRUCTION, "sb", handle_sb, {0}},
	{I_INSTRUCTION, "sh", handle_sh, {0}},
	{ILLEGAL_INSTRUCTION, NULL, NULL, {0}},
	{I_INSTRUCTION, "sw", handle_sw, {0}},
	{ILLEGAL_INSTRUCTION, NULL, NULL, {0}},
	{ILLEGAL_INSTRUCTION, NULL, NULL, {0}},
	{ILLEGAL_INSTRUCTION, NULL, NULL, {0}},
	{ILLEGAL_INSTRUCTION, NULL, NULL, {0}},
	{ILLEGAL_INSTRUCTION, NULL, NULL, {0}},
	{ILLEGAL_INSTRUCTION, NULL, NULL, {0}},
	{ILLEGAL_INSTRUCTION, NULL, NULL, {0}},
	{ILLEGAL_INSTRUCTION, NULL, NULL, {0}},
	{ILLEGAL_INSTRUCTION, NULL, NULL, {0}},
	{ILLEGAL_INSTRUCTION, NULL, NULL, {0}},
	{ILLEGAL_INSTRUCTION, NULL, NULL, {0}},
	{ILLEGAL_INSTRUCTION, NULL, NULL, {0}},
	{ILLEGAL_INSTRUCTION, NULL, NULL, {0}},
	{ILLEGAL_INSTRUCTION, NULL, NULL, {0}},
	{ILLEGAL_INSTRUCTION, NULL, NULL, {0}},
	{ILLEGAL_INSTRUCTION, NULL, NULL, {0}},
	{ILLEGAL_INSTRUCTION, NULL, NULL, {0}},
	{ILLEGAL_INSTRUCTION, NULL, NULL, {0}},
	{ILLEGAL_INSTRUCTION, NULL, NULL, {0}},
	{ILLEGAL_INSTRUCTION, NULL, NULL, {0}},
};

R_funct_entry_t R_functs[] =
{
	/*position in array is funct*/
	{"sll", TRUE, handle_sll},
	{NULL, FALSE, NULL},
	{"srl", TRUE, handle_srl},
	{"sra", TRUE, handle_sra},
	{"sllv", TRUE, handle_sllv},
	{NULL, FALSE, NULL},
	{"srlv", TRUE, handle_srlv},
	{"srav", TRUE, handle_srav},
	{"jr", FALSE, handle_jr},
	{"jalr", FALSE, handle_jalr},
	{NULL, FALSE, NULL},
	{NULL, FALSE, NULL},
	{"syscall", FALSE, handle_syscall},
	{NULL, FALSE, NULL},
	{NULL, FALSE, NULL},
	{NULL, FALSE, NULL},
	{"mfhi", FALSE, handle_mfhi},
	{"mthi", FALSE, handle_mthi},
	{"mflo", FALSE, handle_mflo},
	{"mtlo", FALSE, handle_mtlo},
	{NULL, FALSE, NULL},
	{NULL, FALSE, NULL},
	{NULL, FALSE, NULL},
	{NULL, FALSE, NULL},
	{"mult", FALSE, handle_mult},
	{"multu", FALSE, handle_multu},
	{"div", FALSE, handle_div},
	{"divu", FALSE, handle_divu},
	{NULL, FALSE, NULL},
	{NULL, FALSE, NULL},
	{NULL, FALSE, NULL},
	{NULL, FALSE, NULL},
	{"add", FALSE, handle_add},
	{"addu", FALSE, handle_addu},
	{"sub", FALSE, handle_sub},
	{"subu", FALSE, handle_subu},
	{"and", FALSE, handle_and},
	{"or", FALSE, handle_or},
	{"xor", FALSE, handle_xor},
	{"nor", FALSE, handle_nor},
	{NULL, FALSE, NULL},
	{NULL, FALSE, NULL},
	{"slt", FALSE, handle_slt},
	{"sltu", FALSE, handle_sltu},
	{NULL, FALSE, NULL},
	{NULL, FALSE, NULL},
	{NULL, FALSE, NULL},
	{NULL, FALSE, NULL},
	{NULL, FALSE, NULL},
	{NULL, FALSE, NULL},
	{NULL, FALSE, NULL},
	{NULL, FALSE, NULL},
	{NULL, FALSE, NULL},
	{NULL, FALSE, NULL},
	{NULL, FALSE, NULL},
	{NULL, FALSE, NULL},
	{NULL, FALSE, NULL},
	{NULL, FALSE, NULL},
	{NULL, FALSE, NULL},
	{NULL, FALSE, NULL},
	{NULL, FALSE, NULL},
	{NULL, FALSE, NULL},
	{NULL, FALSE, NULL},
	{NULL, FALSE, NULL},
};

char* register_names[] = {
	"zero",
	"at",
	"v0",
	"v1",
	"a0",
	"a1",
	"a2",
	"a3",
	"t0",
	"t1",
	"t2",
	"t3",
	"t4",
	"t5",
	"t6",
	"t7",
	"s0",
	"s1",
	"s2",
	"s3",
	"s4",
	"s5",
	"s6",
	"s7",
	"t8",
	"t9",
	"k0",
	"k1",
	"gp",
	"sp",
	"fp",
	"ra"
};
