#include "instructions.h"
instruction_entry_t instructions[] =
{
	{0x00, R_INSTRUCTION, NULL},
	{0x02, J_INSTRUCTION, "j"},
	{0x03, J_INSTRUCTION, "jal"},
	{0x04, I_INSTRUCTION, "beq"},
	{0x05, I_INSTRUCTION, "bne"},
	{0x06, I_INSTRUCTION, "blez"},
	{0x07, I_INSTRUCTION, "bgtz"},
	{0x08, I_INSTRUCTION, "addi"},
	{0x09, I_INSTRUCTION, "addiu"},
	{0x0A, I_INSTRUCTION, "slti"},
	{0x0B, I_INSTRUCTION, "sltiu"},
	{0x0C, I_INSTRUCTION, "andi"},
	{0x0D, I_INSTRUCTION, "ori"},
	{0x0F, I_INSTRUCTION, "lui"},
	{0x10, R_INSTRUCTION, "mfc0"},
	{0x20, I_INSTRUCTION, "lb"},
	{0x23, I_INSTRUCTION, "lw"},
	{0x24, I_INSTRUCTION, "lbu"},
	{0x25, I_INSTRUCTION, "lhu"},
	{0x28, I_INSTRUCTION, "sb"},
	{0x29, I_INSTRUCTION, "sh"},
	{0x2B, I_INSTRUCTION, "sw"},
};

R_funct_entry_t R_functs[] =
{
	{0x00, "sll", TRUE},
	{0x1A, "div", FALSE},
	{0x1B, "divu", FALSE},
	{0x02, "srl", TRUE},
	{0x2A, "slt", FALSE},
	{0x2B, "sltu", FALSE},
	{0x03, "sra", TRUE},
	{0x08, "jr", FALSE},
	{0x09, "jalr", FALSE},
	{0x10, "mfhi", FALSE},
	{0x11, "mthi", FALSE},
	{0x12, "mflo", FALSE},
	{0x13, "mtlo", FALSE},
	{0x18, "mult", FALSE},
	{0x19, "multu", FALSE},
	{0x20, "add", FALSE},
	{0x21, "addu", FALSE},
	{0x22, "sub", FALSE},
	{0x23, "subu", FALSE},
	{0x24, "and", FALSE},
	{0x25, "or", FALSE},
	{0x26, "xor", FALSE},
	{0x27, "nor", FALSE},
};

char* register_names[] = {
	"zero",
	"at",
	"v0",
	"v1",
	"a0",
	"a1",
	"a2",
	"a3",
	"t0",
	"t1",
	"t2",
	"t3",
	"t4",
	"t5",
	"t6",
	"t7",
	"s0",
	"s1",
	"s2",
	"s3",
	"s4",
	"s5",
	"s6",
	"s7",
	"t8",
	"t9",
	"k0",
	"k1",
	"gp",
	"sp",
	"fp",
	"ra"
};
